[package]
name = "mpc-ristretto"
description = "A library for performing secure multiparty computation using the Ristretto group."
version = "0.1.0"
keywords = ["mpc", "crypto", "cryptography"]
homepage = "https://renegade.fi"
authors = ["Joey Kraut <joey@renegade.fi>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/renegade-fi/mpc-ristretto"
license = "MIT OR Apache-2.0"

[lib]
name = "mpc_ristretto"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false

[dependencies]
async-std = "1.12"
async-trait = "0.1"
bytes = "1.2"
clear_on_drop = "0.2"
curve25519-dalek = { version = "2", features = ["serde"] }
digest = "0.10"
futures = "0.3"
itertools = "0.10"
rand_core = "0.5.1"
rcgen = "0.9"
rustls = { version = "0.20", features = ["dangerous_configuration"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = { version = "0.8" }
subtle = "2.4.1"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
typenum = "1.15"
quinn = { version = "0.9", features = ["tls-rustls", "native-certs"] }
zeroize = "1.3"

[dev-dependencies]
clap = { version = "3.2.8", features = ["derive"] }
colored = "2"
dns-lookup = "1.0"
inventory = "0.3"
rand = "0.8"