[package]
name = "mpc-ristretto"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpc_ristretto"
path = "src/lib.rs"

[[bin]]
name = "integration-tests"
path = "integration/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12"
async-trait = "0.1"
bytes = "1.2"
clap = { version = "3.2.8", features = ["derive"] }
colored = { version = "2" }
curve25519-dalek = "^3"
dns-lookup = { version = "1.0" }
futures = "0.3"
hyper = "0.14"
rand_core = "0.5.1"
rcgen = "0.9"
rouille = "3.5"
rustls = { version = "0.20", features = ["dangerous_configuration"] }
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
quinn = { version = "0.8", features = ["tls-rustls", "native-certs"] }
qp2p = { version = "0.30" }