[package]
name = "mpc-ristretto"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpc_ristretto"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12"
async-trait = "0.1"
bytes = "1.2"
clear_on_drop = "0.2"
curve25519-dalek = "2"
digest = "0.10"
futures = "0.3"
itertools = "0.10"
rand_core = "0.5.1"
rcgen = "0.9"
rustls = { version = "0.20", features = ["dangerous_configuration"] }
sha3 = { version = "0.8" }
subtle = "2.4.1"
typenum = "1.15"
quinn = { version = "0.9", features = ["tls-rustls", "native-certs"] }
zeroize = "1.3"

[dev-dependencies]
clap = { version = "3.2.8", features = ["derive"] }
colored = "2"
dns-lookup = "1.0"
inventory = "0.3"
rand = "0.8"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }